/**
 * Created by yinchong on 2018/9/14
 */
'use strict';

//language
export const LOAD_LANGUAGE_SUCCESS = 'LOAD_LANGUAGE_SUCCESS';
export const SET_LANGUAGE_SUCCESS = 'SET_LANGUAGE_SUCCESS';

//loading actions
export const CREATE_KEYSTORE_LOADING = 'CREATE_KEYSTORE_LOADING';
export const IMPORT_KEYSTORE_LOADING = 'IMPORT_KEYSTORE_LOADING';
export const EXPORT_KEYSTORE_LOADING = 'EXPORT_KEYSTORE_LOADING';

export const QUERY_NOTEBOOK_LOADING = 'QUERY_NOTEBOOK_LOADING';
export const QUERY_NOTE_LOADING = 'QUERY_NOTE_LOADING';

export const UPSERT_NOTE_LOADING = 'UPSERT_NOTE_LOADING';
export const UNLOCK_NOTE_LOADING = 'UNLOCK_NOTE_LOADING';
export const QUERY_PROFILE_BALANCE_LOADING = 'QUERY_PROFILE_BALANCE_LOADING';
export const QUERY_IDENTITY_BALANCE_LOADING = 'QUERY_IDENTITY_BALANCE_LOADING';

//identity actions
export const CREATE_IDENTITY_SUCCESS = 'CREATE_IDENTITY_SUCCESS';
export const CREATE_IDENTITY_FAIL = 'CREATE_IDENTITY_FAIL';
export const DELETE_IDENTITY_SUCCESS = 'DELETE_IDENTITY_SUCCESS';
export const DELETE_IDENTITY_FAIL = 'DELETE_IDENTITY_FAIL';
export const IMPORT_IDENTITY_SUCCESS = 'IMPORT_IDENTITY_SUCCESS';
export const IMPORT_IDENTITY_FAIL = 'IMPORT_IDENTITY_FAIL';
export const IMPORT_IDENTITY_TYPE = 'IMPORT_IDENTITY_TYPE';
export const EXPORT_IDENTITY_SUCCESS = 'EXPORT_IDENTITY_SUCCESS';
export const EXPORT_IDENTITY_FAIL = 'EXPORT_IDENTITY_FAIL';

export const LOAD_IDENTITY = 'LOAD_IDENTITY';
export const LOGOUT_IDENTITY_SUCCESS = 'LOGOUT_IDENTITY_SUCCESS';
export const LOGOUT_IDENTITY_FAIL = 'LOGOUT_IDENTITY_FAIL';
export const SWITCH_IDENTITY = 'SWITCH_IDENTITY';
export const VIEW_IDENTITY = 'VIEW_IDENTITY';

export const GET_IDENTITY_BALANCE = 'GET_IDENTITY_BALANCE';
export const GET_PROFILE_BALANCE = 'GET_PROFILE_BALANCE';
export const UPDATE_IDENTITY_ALIAS = 'UPDATE_IDENTITY_ALIAS';
export const INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';

//notebooks actions
export const QUERY_NOTEBOOKS = 'QUERY_NOTEBOOKS';
export const QUERY_NOTES = 'QUERY_NOTES';

export const UPSERT_GAS = 'UPSERT_GAS';
export const UPSERT_NOTE_SUCCESS = 'UPSERT_NOTE_SUCCESS';
export const UPSERT_NOTE_FAIL = 'UPSERT_NOTE_FAIL';
export const UPSERT_NOTEBOOK_SUCCESS = 'UPSERT_NOTEBOOK_SUCCESS';
export const UPSERT_NOTEBOOK_FAIL = 'UPSERT_NOTEBOOK_FAIL';

export const UNLOCK_NOTEBOOK_SUCCESS = 'UNLOCK_NOTEBOOK_SUCCESS';
export const UNLOCK_NOTEBOOK_FAIL = 'UNLOCK_NOTEBOOK_FAIL';
export const UNLOCK_NOTE_SUCCESS = 'UNLOCK_NOTE_SUCCESS';
export const UNLOCK_NOTE_FAIL = 'UNLOCK_NOTE_FAIL';

//block chain
export const QUERY_TRANSACTION = 'QUERY_TRANSACTION';
export const QUERY_BLOCK = 'QUERY_BLOCK';
export const SWITCH_NODE = 'SWITCH_NODE';
export const GET_NODE = 'GET_NODE';

//about
export const DONATE_MODAL = 'DONATE_MODAL';

//eos
export const EOS_RAM_LOADING = 'EOS_RAM_LOADING';
export const EOS_STAKE_LOADING = 'EOS_STAKE_LOADING';
export const EOS_RESOURCES_LOADING = 'EOS_RESOURCES_LOADING';
export const EOS_RAM_TYPE = 'EOS_RAM_TYPE';
export const EOS_STAKE_TYPE = 'EOS_STAKE_TYPE';
export const EOS_GET_ACCOUNT = 'EOS_GET_ACCOUNT';
export const EOS_GET_BALANCE = 'EOS_GET_BALANCE';
export const EOS_GET_PRICE = 'EOS_GET_PRICE';
export const EOS_UPDATA_EXTRA = 'EOS_UPDATA_EXTRA';
export const EOS_BUY_RAM_SUCCESS = 'EOS_BUY_RAM_SUCCESS';
export const EOS_BUY_RAM_FAIL = 'EOS_BUY_RAM_FAIL';
export const EOS_SELL_RAM_SUCCESS = 'EOS_SELL_RAM_SUCCESS';
export const EOS_SELL_RAM_FAIL = 'EOS_SELL_RAM_FAIL';
export const EOS_STAKE_SUCCESS = 'EOS_STAKE_SUCCESS';
export const EOS_STAKE_FAIL = 'EOS_STAKE_FAIL';
export const EOS_UNSTAKE_SUCCESS = 'EOS_UNSTAKE_SUCCESS';
export const EOS_UNSTAKE_FAIL = 'EOS_UNSTAKE_FAIL';
